language: csharp
solution: F1Interface.sln
mono: none
dotnet: 5.0.103
jobs:
  include:
    - stage: build
      script: dotnet build
    - stage: unit-tests
      script: dotnet test 
stages:
  - build
  - test