name: .NET

on:
  push:
    branches: [ main ]
    tags:
      - "?.?.?"
      - "?.?.?-alpha"
      - "?.?.?-beta"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      if: success() && startsWith(github.ref, 'refs/tags/')
      run: dotnet pack -c Release -o NuGet/ /p:Version=${GITHUB_REF#refs/*/}
    - name: Publish
      if: success() && startsWith(github.ref, 'refs/tags/')
      env:
        NUGETKEY: ${{ secrets.NUGETKEY }}
      run: |
        cd NuGet/
        dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k $NUGETKEY